name:                cmake-syntax
version:             0.1.0.0
github:              "0xd34df00d/cmake-syntax"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2019 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Parser for the CMake syntax (CMakeLists.txt and .cmake files)
category:            Language

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/cmake-syntax#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- raw-strings-qq
- trifecta

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  cmake-syntax-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmake-syntax
    - hspec

executables:
  dump-ast-exe:
    main:                DumpAst.hs
    source-dirs:         ./
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmake-syntax
